apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: firecrawl
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: trieve-pull-secret
      containers:
        - name: worker
          image: {{ printf "trieve/firecrawl:%s" $.Values.firecrawl_tag }}
          imagePullPolicy: Always
          args: ["pnpm", "run", "workers"]
          resources:
            requests:
              memory: "500Mi"
          env:
            {{- if .Values.redisSecret.name }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redisSecret.name }}
                  key: {{ .Values.redisSecret.key }}
            {{- end }}
          envFrom:
            - secretRef:
                name: firecrawl-config
