kind: Service
apiVersion: v1
metadata:
  name: chat-service
  {{ with $.Values.domains.chat.serviceAnnotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{ end -}}
  labels:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: chat
  selector:
    app.kubernetes.io/name: chat
    app.kubernetes.io/instance: {{ .Release.Name }}
