kind: Service
apiVersion: v1
metadata:
  name: server-service
  {{ with .Values.domains.server.serviceAnnotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{ end -}}
  labels:
    app.kubernetes.io/name: server-service
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: server
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: {{ $.Release.Name }}
