apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-redis-firecrawl
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: clean-redis-firecrawl
    {{- with .Values.global.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- with .Values.global.additionalLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          annotations:
            {{- with .Values.global.additionalAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: curl-container
              image: curlimages/curl:7.88.1
              args:
                - /bin/sh
                - -c
                - curl http://firecrawl-api:3002/admin/@/clean-before-24h-complete-jobs
