apiVersion: v1
kind: Secret
metadata:
  name: firecrawl-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.global.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- if $.Values.num_workers_per_queue }}
  NUM_WORKERS_PER_QUEUE: {{ $.Values.num_workers_per_queue | quote | b64enc }}
  {{- end }}
  PORT: {{ "3002" | b64enc }}
  HOST: {{ "0.0.0.0" | b64enc }}
  {{- if $.Values.redisUri }}
  REDIS_URL: {{ $.Values.redisUri | b64enc }}
  REDIS_RATE_LIMIT_URL: {{ $.Values.redisUri | b64enc }}
  {{- end }}
  PLAYWRIGHT_MICROSERVICE_URL: {{ "http://playwright-service:3000/scrape" | b64enc }}
  USE_DB_AUTHENTICATION: {{ "false" | b64enc }}
  HDX_NODE_BETA_MODE: {{ "1" | b64enc }}
  LOGGING_LEVEL: {{ "TRACE" | b64enc }}
  LOG_LEVEL: {{ "TRACE" | b64enc }}
  {{- if $.Values.scrapingBeeApiKey }}
  SCRAPING_BEE_API_KEY: {{ $.Values.scrapingBeeApiKey | b64enc }}
  {{- end }}
  BULL_AUTH_KEY: {{ "QA==" | b64enc }}
