apiVersion: v1
kind: Secret
metadata:
  name: trieve-unified-secret
  namespace: trieve # Ensure this is the correct namespace
stringData:
  # LLM API Keys
  # openrouter.ai api key (optional)
  llmApiKey: 
  # OpenAI api key
  openaiApiKey: 
  
  # S3 Credentials (ensure you also update s3.endpoint, s3.region, s3.bucket in values.yaml)
  s3AccessKey: 
  s3SecretKey: 
  
  # Other API Keys
  adminApiKey: 
  # jina code api key (optional for jina-code embedding model)
  jinaCodeApiKey: jina_************************************************************
  
  # OIDC and Database
  oidcClientSecret: 

  clickhousePassword: clickhouse

  # SMTP
  smtpPassword: ""

  redisPassword: "moreComplexPassword"
  redisUrl: "redis://:moreComplexPassword@trieve-local-redis-master:6379"

  pdf2mdInternalAuth: "pdf2mdPassword"
