{{- include "trieve.worker.deployment" (dict 
  "name" "delete-worker"
  "replicas" ($.Values.containers.delete_worker.replicas | default 0)
  "image" (dict 
    "repository" $.Values.containers.delete_worker.repository
    "tag" $.Values.containers.delete_worker.tag
  )
  "resources" $.Values.containers.delete_worker.resources
  "Values" $.Values
  "Release" $.Release
  "Template" $.Template
  "Chart" $.Chart
  "env" (list
    (dict
      "name" "DELETE_CHUNK_BATCH_SIZE" 
      "value" $.Values.config.delete_worker.batch_size)
  )
)
-}}
