{{- if not .Values.config.asSecret }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf2md-config
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- with .Values.global.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  REDIS_URL: {{ include "pdf2md.redisUrl" . | indent 2 }}

  # Clickhouse
  CLICKHOUSE_URL: {{ $.Values.clickhouse.connection.clickhouseUrl }}
  CLICKHOUSE_DB: {{ $.Values.clickhouse.connection.clickhouseDB }}
  CLICKHOUSE_USER: {{ $.Values.clickhouse.connection.clickhouseUser }}
  CLICKHOUSE_PASSWORD: {{ $.Values.clickhouse.connection.clickhousePassword }}

  # S3
  S3_ENDPOINT: {{ $.Values.s3.endpoint }}
  S3_ACCESS_KEY: {{ $.Values.s3.accessKey }}
  S3_SECRET_KEY: {{ $.Values.s3.secretKey }}
  S3_BUCKET: {{ $.Values.s3.bucket }}
  AWS_REGION: {{ $.Values.s3.region }}

  # PDF2MD conversion worker services
  LLM_BASE_URL: {{ $.Values.config.llm.baseUrl }}
  LLM_API_KEY: {{ $.Values.config.llm.apiKey }}
  LLM_MODEL: {{ $.Values.config.llm.model }}

  # PDF2MD HTTP API server
  API_KEY: {{ $.Values.config.pdf2md.apiKey }}

  CHUNKR_API_URL: {{ $.Values.config.chunkr.baseUrl }}
  CHUNKR_API_KEY: {{ $.Values.config.chunkr.apiKey }}
{{- end }}

