{{- range $.Values.containers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- with $.Values.global.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $.Values.config.asSecret }}
    checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
    {{- else }}
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
    {{- end }}
    {{- with $.Values.global.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
        {{- if $.Values.config.asSecret }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ printf "%s/%s:%s" (default "trieve" .image.registry) .image.repository (default $.Chart.AppVersion .image.tag) }}
          {{- if .image.pullPolicy }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- end }}
          {{- if .ports }}
          ports:
            {{- toYaml .ports | nindent 10 }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          env:
            {{- if $.Values.s3.accessKeyRef.enabled }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.s3.accessKeyRef.secretName }}
                  key: {{ $.Values.s3.accessKeyRef.secretKey }}
            {{- end }}
            {{- if $.Values.s3.secretKeyRef.enabled }}
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.s3.secretKeyRef.secretName }}
                  key: {{ $.Values.s3.secretKeyRef.secretKey }}
            {{- end }}
            {{- if $.Values.config.llm.apiKeyRef.enabled }}
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.config.llm.apiKeyRef.secretName }}
                  key: {{ $.Values.config.llm.apiKeyRef.secretKey }}
            {{- end }}
            {{- if $.Values.config.pdf2md.apiKeyRef.enabled }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.config.pdf2md.apiKeyRef.secretName }}
                  key: {{ $.Values.config.pdf2md.apiKeyRef.secretKey }}
            {{- end }}
            {{- if $.Values.env }}
            {{- toYaml $.Values.env | nindent 12 }}
            {{- end }}
            {{- if and $.Values.config.chunkr.apiKeyRef $.Values.config.chunkr.apiKeyRef.enabled }}
            - name: CHUNKR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.config.chunkr.apiKeyRef.secretName }}
                  key: {{ $.Values.config.chunkr.apiKeyRef.secretKey }}
            {{- end }}
          envFrom:
            {{- if $.Values.config.asSecret }}
            - secretRef:
                name: pdf2md-config
            {{- else }}
            - configMapRef:
                name: pdf2md-config
            {{- end }}
            {{- if $.Values.envFrom }}
            {{- toYaml $.Values.envFrom | nindent 12 }}
            {{- end }}
---
{{- end }}
