apiVersion: v1
kind: Service
metadata:
  name: pdf2md-service
  labels:
    app.kubernetes.io/name: pdf2md
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pdf2md-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
