apiVersion: v1
kind: Service
metadata:
  name: pdf2md-service
  labels:
    app.kubernetes.io/name: pdf2md
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.global.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pdf2md-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
