{{- range $.Values.containers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ printf "%s/%s:%s" (default "trieve" .image.registry) .image.repository (default $.Chart.AppVersion .image.tag) }}
          {{- if .image.pullPolicy }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- end }}
          {{- if .ports }}
          ports:
            {{- toYaml .ports | nindent 10 }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: pdf2md-config
---
{{- end }}
