{{- if .Values.config.asSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: pdf2md-config
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
type: Opaque
data:
  REDIS_URL: {{ include "pdf2md.redisUrl" . | b64enc | quote }}

  # Clickhouse
  CLICKHOUSE_URL: {{ $.Values.clickhouse.connection.clickhouseUrl | b64enc | quote }}
  CLICKHOUSE_DB: {{ $.Values.clickhouse.connection.clickhouseDB | b64enc | quote }}
  CLICKHOUSE_USER: {{ $.Values.clickhouse.connection.clickhouseUser | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ $.Values.clickhouse.connection.clickhousePassword | b64enc | quote }}

  # S3
  S3_ENDPOINT: {{ $.Values.s3.endpoint | b64enc | quote }}
  S3_ACCESS_KEY: {{ $.Values.s3.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ $.Values.s3.secretKey | b64enc | quote }}
  S3_BUCKET: {{ $.Values.s3.bucket | b64enc | quote }}
  AWS_REGION: {{ $.Values.s3.region | b64enc | quote }}

  # PDF2MD conversion worker services
  LLM_BASE_URL: {{ $.Values.config.llm.baseUrl | b64enc | quote }}
  LLM_API_KEY: {{ $.Values.config.llm.apiKey | b64enc | quote }}
  LLM_MODEL: {{ $.Values.config.llm.model | b64enc | quote }}

  # PDF2MD HTTP API server
  API_KEY: {{ $.Values.config.pdf2md.apiKey | b64enc | quote }}

  CHUNKR_API_URL: {{ $.Values.config.chunkr.baseUrl | b64enc | quote }}
  CHUNKR_API_KEY: {{ $.Values.config.chunkr.apiKey | b64enc | quote }}
{{- end }} 