{{- if .Values.containers.ditto_feed_cronjob }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dittofeed-cronjob
  annotations:
    {{- if $.Values.config.trieve.asSecret }}
    checksum/config: {{ include (print $.Template.BasePath "/settings/backend-secrets.yaml") . | sha256sum }}
    {{- else }}
    checksum/config: {{ include (print $.Template.BasePath "/settings/backend-configmap.yaml") . | sha256sum }}
    {{- end }}
  labels:
    app.kubernetes.io/name: dittofeed-cronjob
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  suspend: {{ $.Values.config.trieve.disableCrons }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- with .Values.global.additionalLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          metadata:
            {{- with .Values.global.additionalAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          {{- if $.Values.global.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
          {{- end }}
          containers:
          - name: dittofeed-cronjob
            image: {{ printf "%s/%s:%s" $.Values.global.image.registry $.Values.containers.ditto_feed_cronjob.repository .Values.containers.word_id_cronjob.tag }}
            envFrom:
              {{- if $.Values.config.trieve.asSecret }}
              - secretRef:
                  name: trieve-server-secret
              {{- else }}
              - configMapRef:
                  name: trieve-server-config
              {{- end }}
{{- end }}
