apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-qdrant
  labels:
    app.kubernetes.io/name: sync-qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.containers.sync_qdrant.replicas | default 0 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sync-qdrant
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if $.Values.config.trieve.asSecret }}
        checksum/config: {{ include (print $.Template.BasePath "/settings/backend-secrets.yaml") . | sha256sum }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/settings/backend-configmap.yaml") . | sha256sum }}
        {{- end }}
      labels:
        app.kubernetes.io/name: sync-qdrant
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: sync-qdrant
        image: {{ printf "%s/%s:%s" $.Values.global.image.registry $.Values.containers.sync_qdrant.repository .Values.containers.sync_qdrant.tag }}
        imagePullPolicy: {{ $.Values.global.image.imagePullPolicy }}
        envFrom:
          {{- if $.Values.config.trieve.asSecret }}
          - secretRef:
              name: trieve-server-secret
          {{- else }}
          - configMapRef:
              name: trieve-server-config
          {{- end }}
