apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $.Release.Name }}-trieve-postgres
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}-trieve-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{ toYaml $.Values.clusterSpec | nindent 2 }}
