{{- if not .Values.config.trieve.asSecret -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: trieve-server-config
  labels:
    {{- include "trieve.labels" . | nindent 4 }}
data:
  ADMIN_API_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.get" (dict "path" "adminApiKey" "default" "" "context" $)) "valueRef" .Values.config.trieve.adminApiKeyRef "context" $) | quote }}
  BASE_SERVER_URL: {{ .Values.config.trieve.baseServerUrl | quote }}
  DATABASE_URL: {{ include "trieve.databaseUrl" . | quote }}
  REDIS_URL: {{ include "trieve.redisUrl" . | quote }}
  QDRANT_URL: {{ .Values.qdrant.url | quote }}
  QDRANT_API_KEY: {{ .Values.qdrant.apiKey | quote }}
  CLICKHOUSE_URL: {{ .Values.clickhouse.connection.clickhouseUrl | quote }}
  CLICKHOUSE_DB: {{ .Values.clickhouse.connection.clickhouseDB | quote }}
  CLICKHOUSE_USER: {{ .Values.clickhouse.connection.clickhouseUser | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.connection.clickhousePassword | quote }}
  QUANTIZE_VECTORS: {{ .Values.config.qdrant.quantizeVectors | quote }}
  QDRANT_SHARD_COUNT: {{ .Values.config.qdrant.shardCount | quote }}
  REPLICATION_FACTOR: {{ .Values.config.qdrant.replicationFactor | quote }}
  VECTOR_SIZES: {{ join "," .Values.config.qdrant.vectorSizes | quote }}
  {{- if .Values.config.smtp.relay }}
  SMTP_RELAY: {{ .Values.config.smtp.relay | quote }}
  {{- end }}
  {{- if .Values.config.smtp.username }}
  SMTP_USERNAME: {{ .Values.config.smtp.username | quote }}
  {{- end }}
  SMTP_PASSWORD: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.smtp.get" (dict "path" "password" "default" "" "context" $)) "valueRef" .Values.config.smtp.passwordRef "context" $) | quote }}
  {{- if .Values.config.smtp.emailAddress }}
  SMTP_EMAIL_ADDRESS: {{ .Values.config.smtp.emailAddress | quote }}
  {{- end }}
  OPENAI_API_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.openai.get" (dict "path" "apiKey" "default" "" "context" $)) "valueRef" .Values.config.openai.apiKeyRef "context" $) | quote }}
  LLM_API_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.llm.get" (dict "path" "apiKey" "default" "" "context" $)) "valueRef" .Values.config.llm.apiKeyRef "context" $) | quote }}
  SECRET_KEY: {{ .Values.config.trieve.secretKey | quote }}
  SALT: {{ .Values.config.trieve.salt | quote }}
  {{- if .Values.config.s3.endpoint }}
  S3_ENDPOINT: {{ .Values.config.s3.endpoint | quote }}
  {{- end }}
  S3_ACCESS_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.s3.get" (dict "path" "accessKey" "default" "" "context" $)) "valueRef" .Values.config.s3.accessKeyRef "context" $) | quote }}
  S3_SECRET_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.s3.get" (dict "path" "secretKey" "default" "" "context" $)) "valueRef" .Values.config.s3.secretKeyRef "context" $) | quote }}
  {{- if .Values.config.s3.bucket }}
  S3_BUCKET: {{ .Values.config.s3.bucket | quote }}
  {{- end }}
  {{- if .Values.config.s3.region }}
  AWS_REGION: {{ .Values.config.s3.region | quote }}
  AWS_REGION_CSVJSONL: {{ .Values.config.s3.region | quote }}
  {{- end }}
  COOKIE_SECURE: {{ .Values.config.trieve.cookieSecure | quote }}
  TIKA_URL: http://tika:9998
  OPENAI_BASE_URL: {{ .Values.config.openai.baseUrl | quote }}
  {{- if .Values.config.stripe.secret }}
  STRIPE_SECRET: {{ .Values.config.stripe.secret | quote }}
  {{- end }}
  {{- if .Values.config.stripe.webhookSecret }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.config.stripe.webhookSecret | quote }}
  {{- end }}
  ADMIN_DASHBOARD_URL: {{ .Values.config.vite.dashboardUrl | quote }}
  OIDC_CLIENT_SECRET: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.oidc.get" (dict "path" "clientSecret" "default" "" "context" $)) "valueRef" .Values.config.oidc.clientSecretRef "context" $) | quote }}
  OIDC_CLIENT_ID: {{ .Values.config.oidc.clientId | quote }}
  OIDC_AUTH_REDIRECT_URL: {{ .Values.config.oidc.authRedirectUrl | quote }}
  OIDC_ISSUER_URL: {{ .Values.config.oidc.issuerUrl | quote }}
  BATCH_CHUNK_LIMIT: {{ .Values.config.trieve.batch_limit | default 120 | quote }}
  SPARSE_SERVER_QUERY_ORIGIN: {{ .Values.config.trieve.sparseServerQueryOrigin | quote }}
  SPARSE_SERVER_DOC_ORIGIN: {{ .Values.config.trieve.sparseServerDocOrigin | quote }}
  EMBEDDING_SERVER_ORIGIN: {{ .Values.config.trieve.embeddingServerOrigin | quote }}
  EMBEDDING_SERVER_ORIGIN_BGEM3: {{ .Values.config.trieve.embeddingServerOriginBGEM3 | quote }}
  EMBEDDING_SERVER_ORIGIN_JINA_CODE: {{ .Values.config.trieve.embeddingServerOriginJinaCode | quote }}
  JINA_CODE_API_KEY: {{ .Values.config.trieve.jinaCodeApiKey | quote }}
  RERANKER_SERVER_ORIGIN: {{ .Values.config.trieve.rerankerServerOrigin | quote }}
  UNLIMITED: {{ .Values.config.trieve.unlimited | quote }}
  REDIS_CONNECTIONS: {{ .Values.config.redis.connections | default "3" | quote }}
  USE_ANALYTICS: {{ "true" | quote }}
  BM25_ACTIVE: {{ .Values.config.trieve.bm25Active | quote }}
  SUBTRACE_TOKEN: {{ .Values.config.trieve.subtraceToken | quote }}
  FIRECRAWL_URL: "http://firecrawl-api:3002"
  DITTOFEED_API_KEY: {{ .Values.config.trieve.dittofeedApiKey | quote }}
  CREATE_QDRANT_COLLECTIONS: {{ .Values.config.qdrant.initCollections | quote }}
  CHAT_COMPLETION_TIMEOUT_SECS: {{ .Values.config.trieve.chatCompletionTimeoutSecs | quote }}
  {{- if .Values.config.trieve.youtubeApiKey }}
  YOUTUBE_API_KEY: {{ .Values.config.trieve.youtubeApiKey | quote }}
  {{- end }}
  PAGEFIND_CDN_BASE_URL: {{ .Values.config.trieve.pagefindCdnUrl | quote }}
  BATCH_ETL_URL: {{ .Values.config.trieve.batchEtlUrl | quote }}
  {{- if .Values.pdf2md.enabled }}
  PDF2MD_URL: "http://pdf2md-service:8081"
  PDF2MD_AUTH: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.pdf2md.config.pdf2md.get" (dict "path" "apiKey" "default" "" "context" $)) "valueRef" .Values.pdf2md.config.pdf2md.apiKeyRef "context" $) | quote }}
  {{- end }}
{{- end }}
