{{- if .Values.config.trieve.asSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: trieve-server-secret
  labels:
    {{- include "trieve.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_API_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.get" (dict "path" "adminApiKey" "default" "" "context" $)) "valueRef" .Values.config.trieve.adminApiKeyRef "context" $) | b64enc | quote }}
  BASE_SERVER_URL: {{ .Values.config.trieve.baseServerUrl | b64enc | quote }}
  DATABASE_URL: {{ include "trieve.databaseUrl" . | b64enc | quote }}
  REDIS_URL: {{ include "trieve.redisUrl" . | b64enc | quote }}
  QDRANT_URL: {{ .Values.qdrant.url | b64enc | quote }}
  QDRANT_API_KEY: {{ .Values.qdrant.apiKey | quote | b64enc }}
  CLICKHOUSE_URL: {{ .Values.clickhouse.connection.clickhouseUrl | b64enc | quote }}
  CLICKHOUSE_DB: {{ .Values.clickhouse.connection.clickhouseDB | b64enc | quote }}
  CLICKHOUSE_USER: {{ .Values.clickhouse.connection.clickhouseUser | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.connection.clickhousePassword | b64enc | quote }}
  QUANTIZE_VECTORS: {{ .Values.config.qdrant.quantizeVectors | toString | b64enc | quote }}
  QDRANT_SHARD_COUNT: {{ .Values.config.qdrant.shardCount | toString | b64enc | quote }}
  REPLICATION_FACTOR: {{ .Values.config.qdrant.replicationFactor | toString | b64enc | quote }}
  VECTOR_SIZES: {{ join "," .Values.config.qdrant.vectorSizes | b64enc | quote }}
  {{- if .Values.config.smtp.relay }}
  SMTP_RELAY: {{ .Values.config.smtp.relay | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.smtp.username }}
  SMTP_USERNAME: {{ .Values.config.smtp.username | b64enc | quote }}
  {{- end }}
  SMTP_PASSWORD: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.smtp.get" (dict "path" "password" "default" "" "context" $)) "valueRef" .Values.config.smtp.passwordRef "context" $) | b64enc | quote }}
  {{- if .Values.config.smtp.emailAddress }}
  SMTP_EMAIL_ADDRESS: {{ .Values.config.smtp.emailAddress | b64enc | quote }}
  {{- end }}
  OPENAI_API_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.openai.get" (dict "path" "apiKey" "default" "" "context" $)) "valueRef" .Values.config.openai.apiKeyRef "context" $) | b64enc | quote }}
  LLM_API_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.llm.get" (dict "path" "apiKey" "default" "" "context" $)) "valueRef" .Values.config.llm.apiKeyRef "context" $) | b64enc | quote }}
  SECRET_KEY: {{ .Values.config.trieve.secretKey | b64enc | quote }}
  SALT: {{ .Values.config.trieve.salt | b64enc | quote }}
  {{- if .Values.config.s3.endpoint }}
  S3_ENDPOINT: {{ .Values.config.s3.endpoint | b64enc | quote }}
  {{- end }}
  S3_ACCESS_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.s3.get" (dict "path" "accessKey" "default" "" "context" $)) "valueRef" .Values.config.s3.accessKeyRef "context" $) | b64enc | quote }}
  S3_SECRET_KEY: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.s3.get" (dict "path" "secretKey" "default" "" "context" $)) "valueRef" .Values.config.s3.secretKeyRef "context" $) | b64enc | quote }}
  {{- if .Values.config.s3.bucket }}
  S3_BUCKET: {{ .Values.config.s3.bucket | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.s3.region }}
  AWS_REGION: {{ .Values.config.s3.region | b64enc | quote }}
  AWS_REGION_CSVJSONL: {{ .Values.config.s3.region | b64enc | quote }}
  {{- end }}
  COOKIE_SECURE: {{ .Values.config.trieve.cookieSecure | toString | b64enc | quote }}
  TIKA_URL: {{ "http://tika:9998" | b64enc | quote }}
  OPENAI_BASE_URL: {{ .Values.config.openai.baseUrl | b64enc | quote }}
  {{- if .Values.config.stripe.secret }}
  STRIPE_SECRET: {{ .Values.config.stripe.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.stripe.webhookSecret }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.config.stripe.webhookSecret | b64enc | quote }}
  {{- end }}
  ADMIN_DASHBOARD_URL: {{ .Values.config.vite.dashboardUrl | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ include "trieve.resolveValue" (dict "currentValue" (include "trieve.config.oidc.get" (dict "path" "clientSecret" "default" "" "context" $)) "valueRef" .Values.config.oidc.clientSecretRef "context" $) | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.config.oidc.clientId | b64enc | quote }}
  OIDC_AUTH_REDIRECT_URL: {{ .Values.config.oidc.authRedirectUrl | b64enc | quote }}
  OIDC_ISSUER_URL: {{ .Values.config.oidc.issuerUrl | b64enc | quote }}
  BATCH_CHUNK_LIMIT: {{ .Values.config.trieve.batch_limit | default 120 | toString | b64enc | quote }}
  SPARSE_SERVER_QUERY_ORIGIN: {{ .Values.config.trieve.sparseServerQueryOrigin | b64enc | quote }}
  SPARSE_SERVER_DOC_ORIGIN: {{ .Values.config.trieve.sparseServerDocOrigin | b64enc | quote }}
  EMBEDDING_SERVER_ORIGIN: {{ .Values.config.trieve.embeddingServerOrigin | b64enc | quote }}
  EMBEDDING_SERVER_ORIGIN_BGEM3: {{ .Values.config.trieve.embeddingServerOriginBGEM3 | b64enc | quote }}
  EMBEDDING_SERVER_ORIGIN_JINA_CODE: {{ .Values.config.trieve.embeddingServerOriginJinaCode | b64enc | quote }}
  JINA_CODE_API_KEY: {{ .Values.config.trieve.jinaCodeApiKey | b64enc | quote }}
  RERANKER_SERVER_ORIGIN: {{ .Values.config.trieve.rerankerServerOrigin | b64enc | quote }}
  UNLIMITED: {{ .Values.config.trieve.unlimited | toString | b64enc | quote }}
  REDIS_CONNECTIONS: {{ .Values.config.redis.connections | default "3" | toString | b64enc | quote }}
  USE_ANALYTICS: {{ "true" | b64enc | quote }}
  BM25_ACTIVE: {{ .Values.config.trieve.bm25Active | toString | b64enc | quote }}
  SUBTRACE_TOKEN: {{ .Values.config.trieve.subtraceToken | b64enc | quote }}
  FIRECRAWL_URL: {{ "http://firecrawl-api:3002" | b64enc | quote }}
  DITTOFEED_API_KEY: {{ .Values.config.trieve.dittofeedApiKey | b64enc | quote }}
  CREATE_QDRANT_COLLECTIONS: {{ .Values.config.qdrant.initCollections | toString | b64enc | quote }}
  CHAT_COMPLETION_TIMEOUT_SECS: {{ .Values.config.trieve.chatCompletionTimeoutSecs | toString | b64enc | quote }}
  {{- if .Values.config.trieve.youtubeApiKey }}
  YOUTUBE_API_KEY: {{ .Values.config.trieve.youtubeApiKey | b64enc | quote }}
  {{- end }}
  PAGEFIND_CDN_BASE_URL: {{ .Values.config.trieve.pagefindCdnUrl | b64enc | quote }}
  BATCH_ETL_URL: {{ .Values.config.trieve.batchEtlUrl | b64enc | quote }}
  {{- if .Values.pdf2md.enabled }}
  PDF2MD_URL: {{ "http://pdf2md-service:8081" | b64enc | quote }}
  PDF2MD_AUTH: {{ .Values.pdf2md.config.pdf2md.apiKey | b64enc | quote }}
  {{- end }}
{{- end }} 
