{{- range $index, $service := .Values.embeddings }}
{{- if ne $index 0 }}
---
{{- end }}
{{- $name := (printf "embedding-%s" $service.name) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- if $service.nodeSelector }}
      nodeSelector:
        {{- toYaml $service.nodeSelector | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if $service.affinity }}
      affinity:
        {{- toYaml $service.affinity | nindent 8 }}
      {{- end }}
      {{- if $service.tolerations }}
      tolerations:
        {{- toYaml $service.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
          image: {{ printf "%s/%s:%s" $service.registry $service.repository $service.tag }}
          args: 
            {{ (concat (list "--model-id" $service.model "--revision" $service.revision) $service.args) | toJson }}
          ports:
            - containerPort: 80
{{- if $service.useGpu }}
          resources:
            limits:
              nvidia.com/gpu: 1
{{- end }}
---
{{- if $service.pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: embedding-{{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}
